<?php
// tables
define('ERR_TABLE_NOT_FOUND',100);
define('ERR_TABLE_ALREADY_ASSOCIATED',101);
define('ERR_NOT_ALLOWED_TO_DISSOCIATE',102);
define('ERR_TABLE_IS_LOCKED',103);
define('ERR_TAKEAWAY_SURNAME_NOT_SET',104);
define('ERR_TAKEAWAY_CHECK_SURNAME',105);
define('ERR_CUSTOMER_NOT_SPECIFIED',106);

// orders
define('ERR_ORDER_NOT_FOUND',200);
define('ERR_GENERIC_ORDER_NOT_PRICED_FOUND',201);
define('ERR_SYNCING_SUBORDERS',202);
define('ERR_COULD_NOT_CREATE_ORDER_OBJECT',203);
define('ERR_NO_ORDER_FOUND',204);
define('ERR_NO_ORDER_CHOSEN',205);
define('ERR_NOT_ALLOWED_TO_CHANGE_FIELD',206);

// templates
define('ERR_PARSING_TEMPLATE',300);
define('ERR_NO_TEMPLATE_SET',302);
define('ERR_CANNOT_OPEN_TEMPLATE_FILE',303);
define('ERR_NO_TEMPLATE_VAR_SET',303);

// printing
define('ERR_PRINTING_ERROR',400);
define('ERR_ORDER_NOT_SET_AS_PRINTED',401);
define('ERR_NO_ORDERS_PRINTED_CATEGORY',402);
define('ERR_PRINTER_NOT_FOUND',403);
define('ERR_PRINTER_NOT_FOUND_FOR_SELECTED_TYPE',404);
define('ERR_NO_ORDER_SELECTED',405);
define('ERR_NO_PRINT_DESTINATION_FOUND',406);
define('ERR_COULD_NOT_OPEN_PRINTER', "Controllare il precorso della stampante, impossibile stampare");
define('ERR_NO_SURNAME_OR_VAT_ACCOUNT', "Manca partita iva, intestazione e codice SDI");
define('ERR_CODICE_LOTTERIA', 409);

// mods
define('ERR_MOD_NOT_CREATED',500);

// users
define('ERR_USER_NOT_FOUND',600);
define('ERR_WRONG_PASSWORD',601);
define('ERR_NO_USER_PROVIDED',602);
define('ERR_NO_PASSWORD',601);

// stock
define('ERR_NAME_IS_BLANK',700);
define('ERR_NO_STOCK_OBJECT_CHOSEN',701);
define('ERR_NO_TYPE_SPECIFIED',702);
define('ERR_OBJECT_ALREADY_EXISTS',703);

// upgrades
define('ERR_SQL_UPGRADE_VARIABLE_NOT_AVAILABLE',800);
define('ERR_SQL_CONTINUING',801);

// other
define('ERR_MYSQL',1000);
define('ERR_ACCESS_DENIED',1001);
define('ERR_UNKNOWN',1002);
define('ERR_UNEXPECTED_VERSION_NUMBER',1003);

?>
